version: Build {build}
image: Visual Studio 2015

environment:
    matrix:
        - PlatformToolset: v140_xp

platform:
    - x64
    - x86

configuration:
    - Release Unicode
    - Debug Unicode

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x86" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    parallel: true
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\projects\2015\
    - msbuild ComparePlus.vcxproj /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        Push-AppveyorArtifact "Notepad++\plugins\ComparePlus\ComparePlus.dll" -FileName ComparePlus.dll

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release Unicode" -and $env:PLATFORMTOOLSET -eq "v140_xp") {
            $ZipFileName = "ComparePlus_$($env:APPVEYOR_REPO_TAG_NAME)_$env:PLATFORM.zip"
            Remove-Item .\Notepad++\plugins\ComparePlus\*.pdb
            7z a $ZipFileName .\Notepad++\plugins\ComparePlus\*
        }

artifacts:
  - path: ComparePlus_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: 7/ifzsk2Tk/V63jr6/WyA4HdmukWhg2PD7pCgJma7f/QYuZCsyE6RZ5M3RIr6JVc
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v140_xp
        configuration: Release Unicode
